version: '3.0'
services:
 database:
  image: postgres:15.3
  networks:
    - docker-network
  volumes:
    - database_volume:/volumes/database
  environment:
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=user
    - POSTGRES_DB=tutorial
 producer:
  depends_on:
    database:
      condition: service_started
  build: ./producer_app
  networks: 
    -  "docker-network"

volumes:
  database_volume:


networks:
  docker-network:
    driver: bridge

